#append
a=[1,2,3,4]
"""(a.append(5))
print(a)
a.insert(1,0.5)
print(a)
fruits=["apple","kiwi","banana"]
fruits.sort()
print(fruits)"""

fruits=["apple","kiwi","banana","kiwi"]
a.pop(0)
print(a)
a.clear()
print(a)
fruits.reverse()
print(fruits)
print(fruits.index("kiwi"))
print(fruits.count("kiwi"))